name: Build
on:
  workflow_call: 
    inputs:
      dotnet-version:
        type: string
        default: "8.0.100"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version}}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore

      - name: Pack
        run: dotnet pack --configuration Release -o artifacts --no-build --version-suffix ${{ github.run_number }}